# Generated by Django 2.1.7 on 2020-10-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='dropoff_address',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='end_time',
            new_name='vehicle_color',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='pickup_address',
            new_name='vehicle_contact',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='time_slot',
        ),
    ]
