# Generated by Django 2.1.7 on 2020-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201025_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
